/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package CS225FinalProject.GUI;

import CS225FinalProject.DataStructure.Narrative;
import CS225FinalProject.DataStructure.SimulationController;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.TimeZone;
import java.util.StringTokenizer;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sid
 */
public class NarrativeDialog extends javax.swing.JDialog {

    /**
     * Creates new form addNarrativeDialog
     */
    
    private boolean edit, update;
    private int row;
    private Narrative theNarrative;
    
    DefaultTableModel model;
    
    public NarrativeDialog(java.awt.Frame parent, boolean modal, DefaultTableModel docModel) {
        super(parent, modal);
        initComponents();
        setLocation((getToolkit().getScreenSize().width - getWidth()) / 2,
                    (getToolkit().getScreenSize().height - getHeight()) / 2);
        edit = false;
        update = false;
        model = docModel;
        theNarrative = new Narrative("","","","","");
    }
    
    public NarrativeDialog(java.awt.Frame parent, boolean modal, DefaultTableModel docModel, Narrative n, int r)
    {
        super(parent, modal);
        initComponents();
        setLocation((getToolkit().getScreenSize().width - getWidth()) / 2,
                    (getToolkit().getScreenSize().height - getHeight()) / 2);
        editNarrative(n);
        model = docModel;
        edit = true;
        update = false;
        theNarrative = n;
        row = r;
    }
    
    public NarrativeDialog(java.awt.Frame parent, boolean modal, Narrative n)
    {
        super(parent, modal);
        initComponents();
        edit = false;
        update = false;
        theNarrative = n;
        editNarrative(n);
        setNotEditable();
    }
    
    public void setNotEditable()
    {
        tempField.setEditable(false);
        pulseField.setEditable(false);
        o2Field.setEditable(false);
        respField.setEditable(false);
        fsbsField.setEditable(false);
        siteField.setEditable(false);
        submitButton.setVisible(false);
        cancelButton.setText("Close");
    }
    
    public boolean update()
    { return update; }
    
    public void updateModel()
    {
        theNarrative = createNarrative();
        if(edit)
        {
            model.setValueAt((Object)theNarrative.getNarrative(), row, 2);
            model.setValueAt((Object)theNarrative.getFollowUP(),row,3);
        }
        else
        {
            model.addRow(new String[] { theNarrative.getDate(), theNarrative.getTime(),
                theNarrative.getNarrative(), theNarrative.getFollowUP(), theNarrative.getInitials() } );
        }
    }
    
    public Narrative createNarrative()
    {
        DateFormat dateFormat = new SimpleDateFormat("MM/dd/yy");
        DateFormat timeFormat = new SimpleDateFormat("HH:mma");
        String date = dateFormat.format(Calendar.getInstance(TimeZone.getDefault()).getTime());
        String time = timeFormat.format(Calendar.getInstance(TimeZone.getDefault()).getTime());
        ArrayList<String> values = new ArrayList<String>();
        values.add(tempField.getText());
        values.add(pulseField.getText());
        values.add(o2Field.getText());
        values.add(respField.getText());
        values.add(fsbsField.getText());
        values.add(siteField.getText());
        String narrative = notesTextArea.getText();
        Narrative n =  new Narrative(date,time,narrative,"","");
        n.setValues(values);
        n.setPainValue(painSlider.getValue());
        return n;
    }
    
    public void editNarrative(Narrative n)
    {
       String date = n.getDate();
       
       String time = n.getTime();
       this.setTitle(date + " " + time);
       ArrayList<String> values = n.getValues();
           tempField.setText(values.get(0));
           pulseField.setText(values.get(1));
           o2Field.setText(values.get(2));
           respField.setText(values.get(3));
           fsbsField.setText(values.get(4));
           siteField.setText(values.get(5));
           painSlider.setValue(n.getPainValue());
       
       notesTextArea.setText(n.getNarrative());
       
       initialLabel.setText(n.getInitials());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tempField = new javax.swing.JTextField();
        tempLabel = new javax.swing.JLabel();
        temp2Label = new javax.swing.JLabel();
        pulseLabel = new javax.swing.JLabel();
        pulseField = new javax.swing.JTextField();
        pulse2Label = new javax.swing.JLabel();
        respLabel = new javax.swing.JLabel();
        respField = new javax.swing.JTextField();
        resp2Label = new javax.swing.JLabel();
        o2Label = new javax.swing.JLabel();
        o2Field = new javax.swing.JTextField();
        o22Label = new javax.swing.JLabel();
        fsbsLabel = new javax.swing.JLabel();
        fsbsField = new javax.swing.JTextField();
        siteLabel = new javax.swing.JLabel();
        siteField = new javax.swing.JTextField();
        painSlider = new javax.swing.JSlider();
        painLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        notesTextArea = new javax.swing.JTextArea();
        textAreaLabel = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        initialLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tempLabel.setText("Temperature");

        temp2Label.setText("*F");

        pulseLabel.setText("Pulse");

        pulse2Label.setText("BPM");

        respLabel.setText("Resp");

        resp2Label.setText("BPM");

        o2Label.setText("O2 sat");

        o22Label.setText("%");

        fsbsLabel.setText("FSBS");

        siteLabel.setText("Site");

        painSlider.setMajorTickSpacing(1);
        painSlider.setMaximum(10);
        painSlider.setOrientation(javax.swing.JSlider.VERTICAL);
        painSlider.setPaintLabels(true);
        painSlider.setPaintTicks(true);
        painSlider.setSnapToTicks(true);
        painSlider.setValue(5);

        painLabel.setText("PAIN SCALE");

        notesTextArea.setColumns(20);
        notesTextArea.setRows(5);
        notesTextArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(notesTextArea);

        textAreaLabel.setText("Related Diagnosis/Reason for medication:");

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel13.setText("Medication Given:   ");

        jLabel14.setText("Initials:  ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tempLabel)
                                    .addComponent(tempField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(temp2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pulseField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pulseLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pulse2Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(49, 49, 49))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(siteField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(siteLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(o2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(o2Label))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(o22Label, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(respField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(resp2Label))
                            .addComponent(fsbsLabel)
                            .addComponent(fsbsField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(respLabel))
                        .addGap(51, 51, 51)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textAreaLabel)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(submitButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cancelButton))
                            .addComponent(jLabel13)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(initialLabel))))
                    .addComponent(painLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {fsbsField, fsbsLabel, o2Field, o2Label, pulseField, pulseLabel, respField, respLabel, siteField, siteLabel, tempField, tempLabel});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(painSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tempLabel)
                                    .addComponent(painLabel))
                                .addGap(4, 4, 4)
                                .addComponent(tempField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(temp2Label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pulseLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pulseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pulse2Label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(o2Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(o22Label)
                            .addComponent(o2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addComponent(respLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(respField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resp2Label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fsbsLabel)
                        .addGap(9, 9, 9)
                        .addComponent(fsbsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(siteLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(siteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(textAreaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(initialLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(submitButton)
                            .addComponent(cancelButton))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed

        updateModel();
        update = true;
        this.dispose();
    }//GEN-LAST:event_submitButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        //</editor-fold>

        /* Create and display the dialog */
      /*  java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NarrativeDialog dialog = new NarrativeDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField fsbsField;
    private javax.swing.JLabel fsbsLabel;
    private javax.swing.JLabel initialLabel;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea notesTextArea;
    private javax.swing.JLabel o22Label;
    private javax.swing.JTextField o2Field;
    private javax.swing.JLabel o2Label;
    private javax.swing.JLabel painLabel;
    private javax.swing.JSlider painSlider;
    private javax.swing.JLabel pulse2Label;
    private javax.swing.JTextField pulseField;
    private javax.swing.JLabel pulseLabel;
    private javax.swing.JLabel resp2Label;
    private javax.swing.JTextField respField;
    private javax.swing.JLabel respLabel;
    private javax.swing.JTextField siteField;
    private javax.swing.JLabel siteLabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel temp2Label;
    private javax.swing.JTextField tempField;
    private javax.swing.JLabel tempLabel;
    private javax.swing.JLabel textAreaLabel;
    // End of variables declaration//GEN-END:variables
}
